name: OPList
main: OPList\Main
author: Ghast Noob
version: 1.0.2
api: [2.0.0]
load: POSTWORLD
description: Xem Danh Sách Quản Trị Viên Của Server.
commands:
 oplist:
  description: Xem Danh Sách Quản Trị Viên Của Server.