---
show-prefix: true
show-messages-onjoin: true
force-hub: false
enable-hub-message: true
hub-message: §bChào Mừng §e{PLAYER}§b Đến Với Lobby Server
force-spawn: false
teleport-on-death: 1
enable-spawn-message: true
spawn-message: §bĐã Dịch Chuyển Tới World {WORLD}
enable-aliases: true
hub:
  world: Lobby+
  X: 134.156800
  "Y": 4.000000
  Z: -148.524800
  Yaw: 155
  Pitch: 30
...
